### ISSUE TITLE
Connection failure with 2.3.0

### ISSUE THREAD

**Issue by punk3r70** [ultrasonic/ultrasonic#180]
## Problem description
2.3.0 won't connect to Subsonic server 6.1.3. Tested with multiple devices. Works with other apps and with Ultrasonic prior to update. 

### Steps to reproduce
Connect to Subsonic 6.1.3.

## System information

 * **Ultrasonic version**: *2.3.0*
 * **Android version**: *7.0*
 * **Device info**: *Samsung Galaxy S7 & Samsung Galaxy Tab S3*

**Comment by ogarcia** [comment]
@Tapchicoma Seems a problem with minify
```
03-20 10:52:48.004 10900-10900/org.moire.ultrasonic W/a: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.moire.ultrasonic.a.a.c.am` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
                                                          at [Source: (okhttp3.ad$a); line: 3, column: 5]
                                                         com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.moire.ultrasonic.a.a.c.am` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
                                                          at [Source: (okhttp3.ad$a); line: 3, column: 5]
                                                             at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(Unknown Source)
                                                             at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(Unknown Source)
                                                             at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(Unknown Source)
                                                             at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(Unknown Source)
                                                             at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(Unknown Source)
                                                             at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(Unknown Source)
                                                             at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(Unknown Source)
                                                             at com.fasterxml.jackson.databind.ObjectReader.readValue(Unknown Source)
                                                             at d.a.a.c.a(Unknown Source)
                                                             at d.a.a.c.a(Unknown Source)
                                                             at d.m.a(Unknown Source)
                                                             at d.g.a(Unknown Source)
                                                             at d.g.a(Unknown Source)
                                                             at d.f$a.a(Unknown Source)
                                                             at org.moire.ultrasonic.service.k.a(Unknown Source)
                                                             at org.moire.ultrasonic.service.a.a(Unknown Source)
                                                             at org.moire.ultrasonic.e.a$1.a(Unknown Source)
                                                             at org.moire.ultrasonic.e.a$1.b(Unknown Source)
                                                             at org.moire.ultrasonic.util.l$3.run(Unknown Source)
```

Still investigating

**Comment by ogarcia** [comment]
@Tapchicoma the debug apk runs well, but the release apk is broken. I don't know why. I will make a new release for google play to rollback and in meantime take a look if you discover that it may be failing

**Comment by ogarcia** [comment]
Rollback to 2.2.2 (as 2.2.3) in Google Store.

Since now, I will to enable beta vesions in Play Store and upload first the apk in beta chanel. If the apk works well and no issues reported then go to stable/production.

**Comment by Tapchicoma** [comment]
Related to enabled minification. Will test it again today and disable obfuscation.

**Comment by ogarcia** [comment]
2.3.0 tag deleted to avoid future problems, superseded by 2.3.1

Now the new versions will be launched in beta channel first. To test it simply opt-in here:
https://play.google.com/apps/testing/org.moire.ultrasonic

We can close this issue.
