### ISSUE TITLE
Ultrasonic crashing on the menu

### ISSUE THREAD

**Issue by 97carmine** [ultrasonic/ultrasonic#233]
## Problem description

The application crashes and closes. The application create a log called ultrasonic-stacktrace.txt that shows the following:

```
Android API level: 25
UltraSonic version name: 2.6.0
UltraSonic version code: 69

java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:663)
	at org.moire.ultrasonic.util.Util.scaleBitmap(Util.java:885)
	at org.moire.ultrasonic.util.LegacyImageLoader.createLargeUnknownImage(LegacyImageLoader.java:127)
	at org.moire.ultrasonic.util.LegacyImageLoader.<init>(LegacyImageLoader.java:83)
	at org.moire.ultrasonic.activity.SubsonicTabActivity.getImageLoader(SubsonicTabActivity.java:808)
	at org.moire.ultrasonic.activity.SelectAlbumActivity$LoadTask.createHeader(SelectAlbumActivity.java:1268)
	at org.moire.ultrasonic.activity.SelectAlbumActivity$LoadTask.done(SelectAlbumActivity.java:1171)
	at org.moire.ultrasonic.activity.SelectAlbumActivity$LoadTask.done(SelectAlbumActivity.java:1117)
	at org.moire.ultrasonic.util.TabActivityBackgroundTask$1$1.run(TabActivityBackgroundTask.java:53)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

### Steps to reproduce

Basically browsing the menu, you do not have to do anything special, it is very common for example, to be playing a song, to enter the albums and to be crashed.

## System information

 * **Ultrasonic version**: *2.6.0*
 * **Android version**: *LineageOS 14.1 (Android 7.1.2)*
 * **Device info**: *HTC 10*

**Comment by Tapchicoma** [comment]
Can you try to enable new image loader in settings ("Feature flags" section) and see if it still happening?

**Comment by 97carmine** [comment]
Same mistake

**Comment by ogarcia** [comment]
Still happening with the [latest version 2.12.0](https://github.com/ultrasonic/ultrasonic/releases/tag/2.12.0)?
