### ISSUE TITLE
"Genres" does not work.

### ISSUE THREAD

**Issue by sprnza** [ultrasonic/ultrasonic#240]
## Problem description

Genres doesn't display anything.

### Steps to reproduce

I use supysonic as backend and this is logs on the server:
```
172.19.0.4 - - [17/Dec/2018 08:09:21] "GET /rest/getGenres.view?u=myUserName&c=Ultrasonic&f=json&v=1.9.0&p=enc:44656E3538393130313430 HTTP/1.1" 200 -
```

Ultrasonic returns "No genres found"

Here is how the response looks like in Postman using the same request:

```
{
    "subsonic-response": {
        "genres": {
            "genre": [
                {
                    "_value_": "Disco"
                },
                {
                    "_value_": "Southern Rock"
                },
                {
                    "_value_": "Rapcore"
                },
                {
                    "_value_": "Smooth Jazz"
                },
                {
                    "_value_": "Americana"
                },
                {
                    "_value_": "Electronic"
                },
                {
                    "_value_": "Melodic Death / Power Metal"
                },
                {
                    "_value_": "Rock & Roll"
                },
                {
                    "_value_": "Avant-Garde"
                },
                {
                    "_value_": "Acid House"
                },
                {
                    "_value_": "Alternative Metal"
                },
                {
                    "_value_": "Heavy Metal"
                },
                {
                    "_value_": "Chillout"
                },
                {
                    "_value_": "Thrash Metal"
                },
                {
                    "_value_": "Ballad"
                },
                {
                    "_value_": "Blue-Eyed Soul"
                },
                {
                    "_value_": "Punk Blues"
                },
                {
                    "_value_": "Oldies"
                },
                {
                    "_value_": "Power Metal"
                },
                {
                    "_value_": "Electro"
                },
                {
                    "_value_": "Technical Death Metal"
                },
                {
                    "_value_": "Podcast"
                },
                {
                    "_value_": "Garage Rock"
                },
                {
                    "_value_": "Country Rock"
                },
                {
                    "_value_": "Instrumental Rock"
                },
                {
                    "_value_": "Trip-Hop"
                },
                {
                    "_value_": "Eurobeat"
                },
                {
                    "_value_": "Opera"
                },
                {
                    "_value_": "Country"
                },
                {
                    "_value_": "Black Metal"
                },
                {
                    "_value_": "Rare Groove"
                },
                {
                    "_value_": "Celtic Punk"
                },
                {
                    "_value_": "Classical"
                },
                {
                    "_value_": "Downtempo"
                },
                {
                    "_value_": "Lo-Fi"
                },
                {
                    "_value_": "Screamo"
                },
                {
                    "_value_": "Punk Rock"
                },
                {
                    "_value_": "Anarcho Punk"
                },
                {
                    "_value_": "Speed Metal"
                },
                {
                    "_value_": "Indie Folk"
                },
                {
                    "_value_": "Industrial Rock"
                },
                {
                    "_value_": "Blues-Rock"
                },
                {
                    "_value_": "Techno"
                },
                {
                    "_value_": "Rhythm And Blues"
                },
                {
                    "_value_": "Western"
                },
                {
                    "_value_": "Pop"
                },
                {
                    "_value_": "Gothic Metal"
                },
                {
                    "_value_": "Folk Rock"
                },
                {
                    "_value_": "Rockabilly"
                },
                {
                    "_value_": "Electronica"
                },
                {
                    "_value_": "Classic Rock"
                },
                {
                    "_value_": "Psychedelic Pop"
                },
                {
                    "_value_": "Jazz-Rock / Fusion"
                },
                {
                    "_value_": "Funk"
                },
                {
                    "_value_": "Hard'n'Heavy"
                },
                {
                    "_value_": "Easy Listening"
                },
                {
                    "_value_": "Canterbury Scene"
                },
                {
                    "_value_": "Symphonic Metal"
                },
                {
                    "_value_": "Alternative"
                },
                {
                    "_value_": "Eurodance"
                },
                {
                    "_value_": "Psychedelic Rock"
                },
                {
                    "_value_": "Nu Metal"
                },
                {
                    "_value_": "Celtic"
                },
                {
                    "_value_": "Jangle Pop"
                },
                {
                    "_value_": "Big Beat"
                },
                {
                    "_value_": "Soul"
                },
                {
                    "_value_": "Art Rock"
                },
                {
                    "_value_": "Rock"
                },
                {
                    "_value_": "Folk Metal"
                },
                {
                    "_value_": "Batcave"
                },
                {
                    "_value_": "Trance"
                },
                {
                    "_value_": "Ambient"
                },
                {
                    "_value_": "Contemporary Classical"
                },
                {
                    "_value_": "Deathrock"
                },
                {
                    "_value_": "Pop / Pop Rock"
                },
                {
                    "_value_": "Industrial Metal"
                },
                {
                    "_value_": "Reggae"
                },
                {
                    "_value_": "Blues"
                },
                {
                    "_value_": "Metalcore"
                },
                {
                    "_value_": "Krautrock"
                },
                {
                    "_value_": "Rap"
                },
                {
                    "_value_": "Alternative Rock"
                },
                {
                    "_value_": "Northern Soul"
                },
                {
                    "_value_": "Rock And Roll"
                },
                {
                    "_value_": "Post-Hardcore"
                },
                {
                    "_value_": "Dance"
                },
                {
                    "_value_": "Gothic Rock"
                },
                {
                    "_value_": "Glam Rock"
                },
                {
                    "_value_": "Pop Rock"
                },
                {
                    "_value_": "Space Rock"
                },
                {
                    "_value_": "Melodic Death Metal"
                },
                {
                    "_value_": "Metal"
                },
                {
                    "_value_": "Soft Rock"
                },
                {
                    "_value_": "Grunge"
                },
                {
                    "_value_": "Melodic Metalcore"
                },
                {
                    "_value_": "Dream Pop"
                },
                {
                    "_value_": "Groove Metal"
                },
                {
                    "_value_": "Folk Punk"
                },
                {
                    "_value_": "Progressive Rock"
                },
                {
                    "_value_": "Drum And Bass"
                },
                {
                    "_value_": "Glam Metal"
                },
                {
                    "_value_": "British Blues"
                },
                {
                    "_value_": "Italo Disco"
                },
                {
                    "_value_": "Power Pop"
                },
                {
                    "_value_": "Death Metal"
                },
                {
                    "_value_": "World Music"
                },
                {
                    "_value_": "Post-Rock"
                },
                {
                    "_value_": "Progressive Folk"
                },
                {
                    "_value_": "Post-Punk"
                },
                {
                    "_value_": "Vocal"
                },
                {
                    "_value_": "Hard Rock"
                },
                {
                    "_value_": "Indie Pop"
                },
                {
                    "_value_": "Electroclash"
                },
                {
                    "_value_": "Indie Rock"
                },
                {
                    "_value_": "Progressive Metal"
                },
                {
                    "_value_": "Instrumental"
                },
                {
                    "_value_": "Synthpop"
                },
                {
                    "_value_": "Punk"
                },
                {
                    "_value_": "Melodic Hardcore"
                },
                {
                    "_value_": "New Wave"
                },
                {
                    "_value_": "Jazz"
                }
            ]
        },
        "status": "ok",
        "version": "1.9.0"
    }
}
```

Dsub is able to retrieve the list of genres just fine.

## System information

 * **Ultrasonic version**: 2.5.0
 * **Android version**: 4.4.4
 * **Device info**: Meizu MX3

**Comment by ogarcia** [comment]
Seem a problem with Ultrasonic JSON parser.
```
12-23 20:22:06.628 27475-29189/org.moire.ultrasonic.debug D/OkHttp: <-- 200 https://supysonic.example.com/rest/getGenres.view?u=username&c=Ultrasonic&f=json&v=1.9.0&p=enc:ENCPASSWD (195ms)
    server: nginx/1.14.2
    date: Sun, 23 Dec 2018 19:20:07 GMT
    content-type: application/json
    content-length: 1589
    access-control-allow-origin: *
    strict-transport-security: max-age=15768000; includeSubdomains; preload
12-23 20:22:06.630 27475-29189/org.moire.ultrasonic.debug D/OkHttp: {"subsonic-response":{"genres":{"genre":[{"_value_":"Classical"},{"_value_":"Electronic"},{"_value_":"Dance"},{"_value_":"Celtic"},{"_value_":"Rock"},{"_value_":"Indie Pop"},{"_value_":"Classic Rock"},{"_value_":"Flamenco"},{"_value_":"Folk Rock"},{"_value_":"Ambient"},{"_value_":"Pop"},{"_value_":"Progressive Rock"},{"_value_":"Nu Metal"},{"_value_":"Funk"},{"_value_":"Grunge"},{"_value_":"Post-Punk"},{"_value_":"New Wave"},{"_value_":"Soundtrack"},{"_value_":"Folk"},{"_value_":"Britpop"},{"_value_":"Hip Hop"},{"_value_":"Latin Pop"},{"_value_":"Punk Rock"},{"_value_":"Indie Rock"},{"_value_":"Alternative Rock"},{"_value_":"Chillout"},{"_value_":"Jazz"},{"_value_":"Electronica"},{"_value_":"Blues"},{"_value_":"Opera"},{"_value_":"Disco"},{"_value_":"Pop Rock"},{"_value_":"Salsa"},{"_value_":"Motown"},{"_value_":"Soul"},{"_value_":"World Fusion"},{"_value_":"Symphonic Metal"},{"_value_":"Neoclassical"},{"_value_":"Hardcore Punk"},{"_value_":"Shoegaze"},{"_value_":"Dub"},{"_value_":"Hard Rock"},{"_value_":"Acapella"},{"_value_":"Chamber Pop"},{"_value_":"House"},{"_value_":"Synthpop"},{"_value_":"Merengue"},{"_value_":"Dark Ambient"},{"_value_":"Progressive Metal"},{"_value_":"Soft Rock"},{"_value_":"Industrial Rock"},{"_value_":"Country"},{"_value_":"Rock En Espa\u00f1ol"},{"_value_":"Electropop"},{"_value_":"Heavy Metal"},{"_value_":"Power Metal"},{"_value_":"Trip-Hop"},{"_value_":"Film Score"},{"_value_":"Rumba"},{"_value_":"Trance"},{"_value_":"Electro"},{"_value_":"Bluegrass"},{"_value_":"Metal"},{"_value_":"Thrash Metal"}]},"status":"ok","version":"1.9.0"}}
12-23 20:22:06.631 27475-29189/org.moire.ultrasonic.debug D/OkHttp: <-- END HTTP (1589-byte body)
12-23 20:22:06.660 27475-29189/org.moire.ultrasonic.debug E/SelectGenreActivity: Failed to load genres
    com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.moire.ultrasonic.api.subsonic.models.Genre] value failed for JSON property value due to missing (therefore NULL) value for creator parameter name which is a non-nullable type
        at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 64] (through reference chain: org.moire.ultrasonic.api.subsonic.response.GenresResponse["genres"]->org.moire.ultrasonic.api.subsonic.response.GenresWrapper["genre"]->java.util.ArrayList[0]->org.moire.ultrasonic.api.subsonic.models.Genre["value"])
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:54)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:529)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:529)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(ObjectReader.java:1703)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
        at org.moire.ultrasonic.service.RESTMusicService.getGenres(RESTMusicService.java:818)
        at org.moire.ultrasonic.service.CachedMusicService.getGenres(CachedMusicService.java:405)
        at org.moire.ultrasonic.activity.SelectGenreActivity$2.doInBackground(SelectGenreActivity.java:121)
        at org.moire.ultrasonic.activity.SelectGenreActivity$2.doInBackground(SelectGenreActivity.java:111)
        at org.moire.ultrasonic.util.TabActivityBackgroundTask$1.run(TabActivityBackgroundTask.java:37)
```

**Comment by ogarcia** [comment]
Revisiting this bug. I don't know why, but it the app run in debug mode works well. The release mode gives the following error:
```
2020-10-04 13:59:52.558 26846-26846/? W/BackgroundTask: Got exception: kotlin.reflect.jvm.internal.KotlinReflectionInternalError: This callable does not support a default call: public constructor Genre(songCount: kotlin.Int = ..., albumCount: kotlin.Int = ..., @com.fasterxml.jackson.annotation.JsonProperty name: kotlin.String) defined in org.moire.ultrasonic.api.subsonic.models.Genre[DeserializedClassConstructorDescriptor@d7cf6db]
    kotlin.reflect.jvm.internal.KotlinReflectionInternalError: This callable does not support a default call: public constructor Genre(songCount: kotlin.Int = ..., albumCount: kotlin.Int = ..., @com.fasterxml.jackson.annotation.JsonProperty name: kotlin.String) defined in org.moire.ultrasonic.api.subsonic.models.Genre[DeserializedClassConstructorDescriptor@d7cf6db]
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(SourceFile:157)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(SourceFile:110)
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(SourceFile:80)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(SourceFile:195)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(SourceFile:488)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(SourceFile:1280)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(SourceFile:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(SourceFile:159)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(SourceFile:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(SourceFile:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(SourceFile:27)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SourceFile:529)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(SourceFile:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(SourceFile:417)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(SourceFile:1280)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(SourceFile:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(SourceFile:159)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SourceFile:529)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(SourceFile:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(SourceFile:449)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(SourceFile:1280)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(SourceFile:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(SourceFile:159)
        at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(SourceFile:1703)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(SourceFile:1608)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(SourceFile:1203)
        at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(SourceFile:75)
        at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(SourceFile:66)
        at retrofit2.ServiceMethod.toResponse(SourceFile:122)
        at retrofit2.OkHttpCall.parseResponse(SourceFile:217)
        at retrofit2.OkHttpCall.execute(SourceFile:180)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(SourceFile:91)
        at org.moire.ultrasonic.service.RESTMusicService.getGenres(SourceFile:835)
        at org.moire.ultrasonic.service.CachedMusicService.getGenres(SourceFile:419)
        at org.moire.ultrasonic.activity.SelectGenreActivity$2.doInBackground(SourceFile:121)
2020-10-04 13:59:52.558 26846-26846/? W/BackgroundTask:     at org.moire.ultrasonic.activity.SelectGenreActivity$2.doInBackground(SourceFile:110)
        at org.moire.ultrasonic.util.TabActivityBackgroundTask$1.run(SourceFile:37)
```

@Tapchicoma or @nitehu  Any idea about why of this? :question: 

UPDATE: Take note that the response is fixed now in server. No more `"_value_"` in json.
```json
{
  "subsonic-response": {
    "genres": {
      "genre": [
        {
          "value": "Classical"
        },
        {
          "value": "Electronic"
        }
      ]
    },
    "status": "ok",
    "version": "1.9.0"
  }
}
```

**Comment by Tapchicoma** [comment]
Most probably something related to proguard/R8 rules.
