### ISSUE TITLE
Tapping on a playlist crashes the app

### ISSUE THREAD

**Issue by Rudd-O** [ultrasonic/ultrasonic#337]
Using Airsonic server, latest Ultrasonic from F-Droid.  Tapping on a playlist on the list of playlists causes a crash and a return to the main menu.  Here is the traceback:

```
10-22 16:51:34.519 32216 32216 E AndroidRuntime: FATAL EXCEPTION: main
10-22 16:51:34.519 32216 32216 E AndroidRuntime: Process: org.moire.ultrasonic, PID: 32216
10-22 16:51:34.519 32216 32216 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setVisibility(int)' on a null object reference
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at org.moire.ultrasonic.view.SongView.setSong(SourceFile:268)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at org.moire.ultrasonic.view.EntryAdapter.getView(SourceFile:111)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2387)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:2067)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.ListView.fillDown(ListView.java:793)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.ListView.fillFromTop(ListView.java:855)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.ListView.layoutChildren(ListView.java:1838)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.AbsListView.onLayout(AbsListView.java:2184)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SourceFile:625)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(SourceFile:530)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at net.simonvt.menudrawer.SlidingDrawer.onLayout(SourceFile:146)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3470)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2938)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: Error reporting crash
10-22 16:51:34.519 32216 32216 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:540)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5182)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at org.moire.ultrasonic.activity.SubsonicTabActivity$SubsonicUncaughtExceptionHandler.uncaughtException(SourceFile:1240)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
10-22 16:51:34.519 32216 32216 I Process : Sending signal. PID: 32216 SIG: 9
10-22 16:51:34.552  1377  1637 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
```

**Comment by Rudd-O** [comment]
OS: GrapheneOS Android 11 latest release on Pixel 4.

**Comment by nitehu** [comment]
I can only guess this is somehow related to what Airsonic returns in the playlist, at least I can't reproduce it.
Could you please attach a detailed debug log starting when you enter into the playlists menu? There is a "Write debug log" option at the end of the Settings which can be turned on to do this.

**Comment by Rudd-O** [comment]
https://github.com/ultrasonic/ultrasonic/blob/645f524ce52b7009579608942e30e5210e37cf6d/ultrasonic/src/main/java/org/moire/ultrasonic/view/SongView.java#L268 when five-star rating is disabled — here is the crash.  When five-star rating is enabled, it crashes here: https://github.com/ultrasonic/ultrasonic/blob/645f524ce52b7009579608942e30e5210e37cf6d/ultrasonic/src/main/java/org/moire/ultrasonic/view/SongView.java#L260 .

**Comment by Rudd-O** [comment]
Looks like the viewHolder is somehow NULL .

**Comment by Rudd-O** [comment]
If it helps, the situation happens with playlists that have **only videos**.  Playlists with only audio or a mix of audio and video, do not crash.  Perhaps there's something in the code that is not instantiating that viewHolder when only videos are displayed.

**Comment by nitehu** [comment]
Thank you, that helped!
I think the problem is that here the ViewHolder's properties may be filled from two different layouts:

https://github.com/ultrasonic/ultrasonic/blob/645f524ce52b7009579608942e30e5210e37cf6d/ultrasonic/src/main/java/org/moire/ultrasonic/view/SongView.java#L132

and in case of videos, some properties of the ViewHolder (like rating) will be null.
I'll get back with a fix soon.

**Comment by Rudd-O** [comment]
Thanks.  This fixed the crash  However, I have to say that downloading playlists that contain videos does result in no videos actually being transcoded and downloaded to the phone, when the *cache* action on the playlist list is engaged.  In https://github.com/nvllsvm/Audinaut , downloading a playlist that contains videos results in the playlist being downloaded, all videos being transcoded by Airsonic to MP3s (that's just my setting, it could be whatevs like an Ogg Vorbis file), and the playlist on the phone correctly points to the transcoded MP3.

**Comment by nitehu** [comment]
I'm not sure yet how video playing works in Ultrasonic, I'm afraid it won't download the video file anyway, also see [this comment](https://github.com/ultrasonic/ultrasonic/issues/241#issuecomment-459463869)
Would you please create a separate issue for this, so it can be investigated further? Maybe it would be a nice enhancement.
