### ISSUE TITLE
Search function triggers Exception

### ISSUE THREAD

**Issue by fiskhandlarn** [ultrasonic/ultrasonic#360]
## Problem description

Whenever I search my library ultrasonic hangs/quits. See excerpt from log below.

### Steps to reproduce

1. Click on Search in the foldout menu
2. Enter search term in input field
3. Press return on soft keyboard

## System information

 * **Ultrasonic version**: 2.17.1
 * **Android version**: 10
 * **Device info**: Samsung Galaxy S10e (SM-G970F)

## Additional notes

This Exception happens twice before ultrasonic force quits:

```
13:23:43.453: E SubsonicTabActivity$SubsonicUncaughtExceptionHandler Uncaught Exception! Android API level: 29
Ultrasonic version name: 2.17.1
Ultrasonic version code: 85


java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.TextView
	at org.moire.ultrasonic.view.ArtistAdapter.getView(SourceFile:87)
	at org.moire.ultrasonic.util.MergeAdapter.getView(SourceFile:248)
	at android.widget.AbsListView.obtainView(AbsListView.java:3271)
	at android.widget.ListView.makeAndAddView(ListView.java:2238)
	at android.widget.ListView.fillDown(ListView.java:838)
	at android.widget.ListView.fillFromTop(ListView.java:900)
	at android.widget.ListView.layoutChildren(ListView.java:1974)
	at android.widget.AbsListView.onLayout(AbsListView.java:3041)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(SourceFile:530)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at net.simonvt.menudrawer.SlidingDrawer.onLayout(SourceFile:146)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1099)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3712)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3164)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
	at android.view.Choreographer.doFrame(Choreographer.java:732)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
 java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.TextView
13:23:43.455: I SubsonicTabActivity$SubsonicUncaughtExceptionHandler Stack trace written to /storage/emulated/0/Android/data/org.moire.ultrasonic/files/ultrasonic-stacktrace.txt
```

**Comment by nitehu** [comment]
Thanks for finding this! 
This bug is related to the Artist list changes, seems we must refactor a bit in the search view too. I'll check if the new Artist view can be added or the old one should be adapted to the new layout.

**Comment by fiskhandlarn** [comment]
Wow, thanks for the quick help! I tested 2.17.2 just now, works perfectly.
