### ISSUE TITLE
Null object reference mPrivateFlags

### ISSUE THREAD

**Issue by jambw** [ultrasonic/ultrasonic#369]
## Problem description
I get this box coming up usually while scrolling through the queue. It's not always the same cause, sometimes it happens on a button press and sometimes it appears by itself. It doesn't 
seem to cause any problems or stop the music playing, it happens maybe once a day.
![Screenshot_20210104-010127](https://user-images.githubusercontent.com/31392624/103493600-37ff4000-4e2a-11eb-838d-784e8a998652.png)

Here is I think the relevant bit of the debug log, let me know if you want/need any more. 
```
01:01:12.387: W BackgroundTask java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4619)
	at android.widget.ListView.findViewTraversal(ListView.java:3857)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4620)
	at android.view.View.findViewById(View.java:24073)
	at android.view.Window.findViewById(Window.java:1405)
	at androidx.appcompat.app.AppCompatDelegateImpl.findViewById(SourceFile:631)
	at androidx.appcompat.app.AppCompatActivity.findViewById(SourceFile:223)
	at org.moire.ultrasonic.activity.SubsonicTabActivity$1$1.doInBackground(SourceFile:263)
	at org.moire.ultrasonic.activity.SubsonicTabActivity$1$1.doInBackground(SourceFile:253)
	at org.moire.ultrasonic.util.SilentBackgroundTask$1.run(SourceFile:44)
 java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference
```
I'm not sure if this is an issue as such as it doesn't seem to stop anything from working, but I thought someone might want to know. I guess you can just close this if it's already known about, I tried searching the previous issues but I couldn't find this.

### Steps to reproduce
Scroll through queue, reorder songs, maybe skip a track? It has occasionally happened when I switched back into the app from another one without me doing anything. I can't really give any more specific information but it happens usually at least once a day, sometimes more.

## System information
Ultrasonic 2.16.0
Android 10
 Moto g(7) power [XT1955-4]

## Additional notes
I am using airsonic-advanced 11.0.0-SNAPSHOT.20200916153357

**Comment by nitehu** [comment]
Wow this bug is really mysterious!
I've found something similar [here](https://stackoverflow.com/questions/33242776/android-viewgroup-crash-attempt-to-read-from-field-int-android-view-view-mview). This maybe caused by that when the background thread runs, something somewhere is still (or is already) null in the activity (viewGroup).

It would be nice to find what it is, but if it can't be reproduced (I for one never seen anything like this error in Ultrasonic) and it doesn't cause any problems, maybe it can be ignored temporarily with a try/catch...
