### ISSUE TITLE
DownloadTask fails with "Unknown or unsupported URL: content://media/external/audio/albumart/-1128604765"

### ISSUE THREAD

**Issue by Sohalt** [ultrasonic/ultrasonic#383]
## Problem description

If I try to download&pin an entire album by selecting all titles in the album and pressing the "pin" button, it starts downloading the first track 
and when it has finished it starts over in an endless loop.

Doing it in 2 steps (first downloading, then pinning) works fine.

It seems the error is because it tries to access external storage, which does not exist.

```
15:42:54.026: I SettingsFragment Enabled debug logging to file 
15:43:03.708: D RESTMusicService Loading cover art for: Entry(id=16745, parent=379, isDirectory=true, title=[em] Live, album=[em] Live, albumId=, artist=[em], artistId=, track=-1, year=2010, genre=Jazz, contentType=, suffix=, transcodedContentType=, transcodedSuffix=, coverArt=16745, size=-1, songCount=null, duration=-1, bitRate=-1, path=, isVideo=false, starred=false, discNumber=-1, type=, created=Tue Jan 30 18:44:22 GMT+01:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:03.881: I FileUtil getSampledBitmap 275 
15:43:04.636: D RESTMusicService Loading cover art for: Entry(id=16754, parent=16745, isDirectory=false, title=Break It, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=10, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27334981, songCount=null, duration=254, bitRate=848, path=[em]/[em] Live/10 Break It.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:41 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:04.792: I FileUtil getSampledBitmap 512 
15:43:08.005: I DownloadQueueSerializer Serialized currentPlayingIndex: 13, currentPlayingPosition: 111968 
15:43:08.005: I CancellableTask Starting thread for DownloadTask (Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null)) 
15:43:08.008: I DownloadFile$DownloadTask Acquired wake lock WakeLock{8aa69f7 held=true, refCount=1} 
15:43:08.012: I FileUtil Serialized object to /data/user/0/org.moire.ultrasonic/cache/downloadstate.ser 
15:43:11.151: I DownloadFile$DownloadTask Downloaded 2,11 MB of Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:14.150: I DownloadFile$DownloadTask Downloaded 4,41 MB of Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:16.359: I DownloadFile$DownloadTask Downloaded 6360000 bytes to /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/[em]/[em] Live/01-Blüten.partial.mp3 
15:43:16.371: D RESTMusicService Loading cover art for: Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:16.604: I FileUtil getSampledBitmap 1080 
15:43:16.655: I Util Renamed /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/[em]/[em] Live/01-Blüten.partial.mp3 to /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/[em]/[em] Live/01-Blüten.mp3 
15:43:16.813: I Util Deleted file /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/[em]/[em] Live/01-Blüten.mp3 
15:43:16.814: W DownloadFile$DownloadTask Failed to download 'Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null)'.
java.lang.UnsupportedOperationException: Unknown or unsupported URL: content://media/external/audio/albumart/-1128604765
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:174)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1183)
	at android.content.ContentResolver.query(ContentResolver.java:1115)
	at android.content.ContentResolver.query(ContentResolver.java:1071)
	at org.moire.ultrasonic.service.MediaStoreService.insertAlbumArt(SourceFile:107)
	at org.moire.ultrasonic.service.MediaStoreService.saveInMediaStore(SourceFile:77)
	at org.moire.ultrasonic.service.DownloadFile$DownloadTask.execute(SourceFile:401)
	at org.moire.ultrasonic.util.CancellableTask$1.run(SourceFile:84)
 java.lang.UnsupportedOperationException: Unknown or unsupported URL: content://media/external/audio/albumart/-1128604765
15:43:16.817: I DownloadFile$DownloadTask Released wake lock WakeLock{8aa69f7 held=false, refCount=0} 
15:43:16.827: I CancellableTask Stopping thread for DownloadTask (Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null)) 
```

### Steps to reproduce

1. select album that is not cached
2. pin album

## System information

 * **Ultrasonic version**: 2.18.0
 * **Android version**: 11
 * **Device info**: Google Pixel 4a

**Comment by ogarcia** [comment]
I cannot reproduce it. But seens a problem with album art. There is an embbeded album art in this song? What size?

**Comment by Sohalt** [comment]
I don't know how to best extract that information.
Here's an example file https://soha.lt/aXXo.mp3 (aXXo under CC-BY-NC license by Binärpilot) that exhibits this behavior.

**Comment by ogarcia** [comment]
Can reproduce it. Full log:
```
2021-03-19 11:20:32.929 19497-21570/org.moire.ultrasonic.debug I/DownloadFile$DownloadTask: Acquired wake lock WakeLock{c0d662e held=true, refCount=1}
2021-03-19 11:20:32.935 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: --> GET http://hell.cor.lan:4040/rest/stream.view?id=9&maxBitRate=0&u=admin&c=Ultrasonic&f=json&v=1.15.0&t=75aacb8773d8d903affda1a9a464330f&s=429C3F4488C862B39864E35318D7BBDF
2021-03-19 11:20:32.936 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: --> END GET
2021-03-19 11:20:32.951 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: <-- 200 http://hell.cor.lan:4040/rest/stream.view?id=9&maxBitRate=0&u=admin&c=Ultrasonic&f=json&v=1.15.0&t=75aacb8773d8d903affda1a9a464330f&s=429C3F4488C862B39864E35318D7BBDF (14ms)
2021-03-19 11:20:32.951 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Set-Cookie: JSESSIONID=113BF49E9EF1B525F31EC92006BCDA07; Path=/; HttpOnly
2021-03-19 11:20:32.951 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Access-Control-Allow-Origin: *
2021-03-19 11:20:32.952 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Set-Cookie: player-61646d696e=2; Max-Age=31536000; Expires=Sat, 19-Mar-2022 10:20:34 GMT; Path=/; HttpOnly
2021-03-19 11:20:32.953 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: ETag: 9
2021-03-19 11:20:32.953 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: X-Content-Duration: 266.0
2021-03-19 11:20:32.954 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: X-Content-Type-Options: nosniff
2021-03-19 11:20:32.955 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: X-XSS-Protection: 1; mode=block
2021-03-19 11:20:32.955 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
2021-03-19 11:20:32.956 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Pragma: no-cache
2021-03-19 11:20:32.956 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Expires: 0
2021-03-19 11:20:32.957 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: X-Frame-Options: SAMEORIGIN
2021-03-19 11:20:32.957 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Content-Type: audio/mpeg
2021-03-19 11:20:32.958 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Content-Length: 6956128
2021-03-19 11:20:32.958 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Date: Fri, 19 Mar 2021 10:20:34 GMT
2021-03-19 11:20:32.959 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Keep-Alive: timeout=60
2021-03-19 11:20:32.960 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: Connection: keep-alive
2021-03-19 11:20:33.760 19497-19531/org.moire.ultrasonic.debug I/ltrasonic.debu: Background concurrent copying GC freed 16486(18MB) AllocSpace objects, 2(40KB) LOS objects, 49% free, 11MB/22MB, paused 289us total 120.356ms
2021-03-19 11:20:34.375 19497-21570/org.moire.ultrasonic.debug D/TimberOkHttpLogger: <-- END HTTP (binary 6956128-byte body omitted)
2021-03-19 11:20:34.450 19497-21570/org.moire.ultrasonic.debug I/DownloadFile$DownloadTask: Downloaded 6956128 bytes to /storage/emulated/0/Android/data/org.moire.ultrasonic.debug/files/music/You can't stop da funk/01-aXXo.partial.mp3
2021-03-19 11:20:34.462 19497-21570/org.moire.ultrasonic.debug I/Util: Renamed /storage/emulated/0/Android/data/org.moire.ultrasonic.debug/files/music/You can't stop da funk/01-aXXo.partial.mp3 to /storage/emulated/0/Android/data/org.moire.ultrasonic.debug/files/music/You can't stop da funk/01-aXXo.mp3
2021-03-19 11:20:34.476 19497-21570/org.moire.ultrasonic.debug I/Util: Deleted file /storage/emulated/0/Android/data/org.moire.ultrasonic.debug/files/music/You can't stop da funk/01-aXXo.mp3
2021-03-19 11:20:34.478 19497-21570/org.moire.ultrasonic.debug W/DownloadFile$DownloadTask: Failed to download 'Entry(id=9, parent=5, isDirectory=false, title=aXXo, album=Nordland, albumId=0, artist=Binärpilot, artistId=0, track=1, year=2010, genre=Unknown, contentType=audio/mpeg, suffix=mp3, transcodedContentType=, transcodedSuffix=, coverArt=5, size=6956128, songCount=null, duration=266, bitRate=195, path=You can't stop da funk/05 aXXo.mp3, isVideo=false, starred=false, discNumber=1, type=music, created=Fri Mar 19 11:00:29 GMT+01:00 2021, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null)'.
    java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/audio/media from pid=19497, uid=10142 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.delete(ContentProviderNative.java:547)
        at android.content.ContentResolver.delete(ContentResolver.java:1691)
        at org.moire.ultrasonic.service.MediaStoreService.deleteFromMediaStore(MediaStoreService.java:89)
        at org.moire.ultrasonic.service.MediaStoreService.saveInMediaStore(MediaStoreService.java:54)
        at org.moire.ultrasonic.service.DownloadFile$DownloadTask.execute(DownloadFile.java:403)
        at org.moire.ultrasonic.util.CancellableTask$1.run(CancellableTask.java:84)
2021-03-19 11:20:34.482 19497-21570/org.moire.ultrasonic.debug I/DownloadFile$DownloadTask: Released wake lock WakeLock{c0d662e held=false, refCount=0}
2021-03-19 11:20:34.489 19497-20154/org.moire.ultrasonic.debug I/CacheCleaner: File system       : 5,14 GB of 11,23 GB available
2021-03-19 11:20:34.490 19497-20154/org.moire.ultrasonic.debug I/CacheCleaner: Cache limit       : 500,00 MB
2021-03-19 11:20:34.491 19497-20154/org.moire.ultrasonic.debug I/CacheCleaner: Cache size before : 6,02 MB
2021-03-19 11:20:34.492 19497-20154/org.moire.ultrasonic.debug I/CacheCleaner: Minimum to delete : 0 B
2021-03-19 11:20:34.493 19497-21570/org.moire.ultrasonic.debug I/LocalMediaPlayer: Next: DOWNLOADING -> DOWNLOADING (null)
2021-03-19 11:20:34.493 19497-21574/org.moire.ultrasonic.debug I/CancellableTask: Starting thread for DownloadTask (Entry(id=9, parent=5, isDirectory=false, title=aXXo, album=Nordland, albumId=0, artist=Binärpilot, artistId=0, track=1, year=2010, genre=Unknown, contentType=audio/mpeg, suffix=mp3, transcodedContentType=, transcodedSuffix=, coverArt=5, size=6956128, songCount=null, duration=266, bitRate=195, path=You can't stop da funk/05 aXXo.mp3, isVideo=false, starred=false, discNumber=1, type=music, created=Fri Mar 19 11:00:29 GMT+01:00 2021, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null))
2021-03-19 11:20:34.494 19497-21570/org.moire.ultrasonic.debug I/CancellableTask: Stopping thread for DownloadTask (Entry(id=9, parent=5, isDirectory=false, title=aXXo, album=Nordland, albumId=0, artist=Binärpilot, artistId=0, track=1, year=2010, genre=Unknown, contentType=audio/mpeg, suffix=mp3, transcodedContentType=, transcodedSuffix=, coverArt=5, size=6956128, songCount=null, duration=266, bitRate=195, path=You can't stop da funk/05 aXXo.mp3, isVideo=false, starred=false, discNumber=1, type=music, created=Fri Mar 19 11:00:29 GMT+01:00 2021, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null))
```

Seems that we have a problem with delete:
```
2021-03-19 11:32:38.119 22315-22315/org.moire.ultrasonic.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.moire.ultrasonic.debug, PID: 22315
    java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/audio/media from pid=22315, uid=10142 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.delete(ContentProviderNative.java:547)
        at android.content.ContentResolver.delete(ContentResolver.java:1691)
        at org.moire.ultrasonic.service.MediaStoreService.deleteFromMediaStore(MediaStoreService.java:89)
        at org.moire.ultrasonic.service.DownloadFile.delete(DownloadFile.java:192)
        at org.moire.ultrasonic.service.MediaPlayerControllerImpl.delete(MediaPlayerControllerImpl.java:422)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment.delete(SelectAlbumFragment.java:1061)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment.access$1100(SelectAlbumFragment.java:62)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment$11.onClick(SelectAlbumFragment.java:255)
        at android.view.View.performClick(View.java:7353)
        at android.view.View.performClickInternal(View.java:7319)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27846)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
2021-03-19 11:32:38.268 22315-22315/org.moire.ultrasonic.debug E/SubsonicUncaughtExceptionHandler: Uncaught Exception! Android API level: 28
    Ultrasonic version name: 2.19.1
    Ultrasonic version code: 90
    
    
    java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/audio/media from pid=22315, uid=10142 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.delete(ContentProviderNative.java:547)
        at android.content.ContentResolver.delete(ContentResolver.java:1691)
        at org.moire.ultrasonic.service.MediaStoreService.deleteFromMediaStore(MediaStoreService.java:89)
        at org.moire.ultrasonic.service.DownloadFile.delete(DownloadFile.java:192)
        at org.moire.ultrasonic.service.MediaPlayerControllerImpl.delete(MediaPlayerControllerImpl.java:422)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment.delete(SelectAlbumFragment.java:1061)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment.access$1100(SelectAlbumFragment.java:62)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment$11.onClick(SelectAlbumFragment.java:255)
        at android.view.View.performClick(View.java:7353)
        at android.view.View.performClickInternal(View.java:7319)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27846)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
2021-03-19 11:32:38.276 22315-22315/org.moire.ultrasonic.debug I/SubsonicUncaughtExceptionHandler: Stack trace written to /storage/emulated/0/Android/data/org.moire.ultrasonic.debug/files/ultrasonic-stacktrace.txt
2021-03-19 11:32:38.354 22315-22315/org.moire.ultrasonic.debug I/Process: Sending signal. PID: 22315 SIG: 9
```

**Comment by ogarcia** [comment]
Another way to reproduce it with worse consequences (application crash):
1. Download any song.
2. Select it.
3. Press the X button (in bottom right) to delete it (the downloaded one).
4. Crash! Boom! Bang!

**Comment by tzugen** [comment]
I can't repoduce unfortunately.
I just find another bug:
```

2021-04-02 09:17:47.123 1631-4014/android.process.media E/SQLiteLog: (1) table album_art has no column named relative_path
2021-04-02 09:17:47.124 1631-4014/android.process.media E/SQLiteDatabase: Error inserting _data=/storage/emulated/0/Music/_.thumbnails/1617347867123.jpg album_id=186 relative_path=Music/.thumbnails/
    android.database.sqlite.SQLiteException: table album_art has no column named relative_path (code 1 SQLITE_ERROR): , while compiling: INSERT INTO album_art(_data,album_id,relative_path) VALUES (?,?,?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1597)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3213)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:2903)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:154)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by tzugen** [comment]
What is this MediaStore used for? So that Android can show the Music in the default Music app?

**Comment by ogarcia** [comment]
> What is this MediaStore used for? So that Android can show the Music in the default Music app?

Maybe legacy code for the use that you comment. IMHO, if you are using default cache storage, it shouldn't be necessary for that music to be shown to other apps

**Comment by tzugen** [comment]
This might be the reason that I see the albums twice in the stock music app...
