### ISSUE TITLE
NPE Crash concerning EqualizerController

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#401]
## Problem description

Unfortunately the stacktrace was not saved (becuase there was already a stacktrace file?)

```

03-20 09:10:57.112 11634 11670 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 11670 (Thread-5), pid 11634 (oire.ultrasonic)
03-20 09:10:57.193 11674 11674 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-20 09:10:57.193 11674 11674 F DEBUG   : LineageOS Version: '17.1-xxxxxxxxxxxxxxx'
03-20 09:10:57.193 11674 11674 F DEBUG   : Build fingerprint: xxxxxxxxxxxxx
03-20 09:10:57.193 11674 11674 F DEBUG   : Revision: '0'
03-20 09:10:57.193 11674 11674 F DEBUG   : ABI: 'arm64'
03-20 09:10:57.194 11674 11674 F DEBUG   : Timestamp: 2021-03-20 09:10:57+0100
03-20 09:10:57.194 11674 11674 F DEBUG   : pid: 11634, tid: 11670, name: Thread-5  >>> org.moire.ultrasonic <<<
03-20 09:10:57.194 11674 11674 F DEBUG   : uid: 10149
03-20 09:10:57.194 11674 11674 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
03-20 09:10:57.194 11674 11674 F DEBUG   : Cause: null pointer dereference
03-20 09:10:57.194 11674 11674 F DEBUG   :     x0  0000007eae03c280  x1  0000007ea7733878  x2  0000007f9e0a6dec  x3  0000000000000065
03-20 09:10:57.194 11674 11674 F DEBUG   :     x4  0000000000000065  x5  0000007f18d1e31a  x6  0000000016084820  x7  0000000000000055
03-20 09:10:57.195 11674 11674 F DEBUG   :     x8  0000000000000000  x9  0000000000000004  x10 0000000000430000  x11 0000007f1a5f6000
03-20 09:10:57.195 11674 11674 F DEBUG   :     x12 0000000000000064  x13 0000000000000002  x14 0000000000000000  x15 0000000000000000
03-20 09:10:57.195 11674 11674 F DEBUG   :     x16 0000007ea7738608  x17 0000007f9c3325bc  x18 0000007ea8078000  x19 0000007ea986f724
03-20 09:10:57.195 11674 11674 F DEBUG   :     x20 0000007eadffe0c0  x21 0000007ea986f518  x22 0000007ea986f508  x23 0000007ea7739000
03-20 09:10:57.195 11674 11674 F DEBUG   :     x24 0000007ea986f730  x25 0000007ea986f520  x26 0000007f1aa69db0  x27 0000007eae0730f0
03-20 09:10:57.195 11674 11674 F DEBUG   :     x28 0000000000000000  x29 0000007ea986f4c0
03-20 09:10:57.195 11674 11674 F DEBUG   :     sp  0000007ea986f490  lr  0000007ea77338e8  pc  0000007f9c3325c4
03-20 09:10:57.407 11674 11674 F DEBUG   : 
03-20 09:10:57.407 11674 11674 F DEBUG   : backtrace:
03-20 09:10:57.407 11674 11674 F DEBUG   :       #00 pc 000000000000f5c4  /system/lib64/libutils.so (android::RefBase::incStrong(void const*) const+8) (BuildId: 6212421b5da38101f8412487a7e3e28e)
03-20 09:10:57.407 11674 11674 F DEBUG   :       #01 pc 00000000000048e4  /system/lib64/libaudioeffect_jni.so (setAudioEffect(_JNIEnv*, _jobject*, android::sp<android::AudioEffect> const&)+108) (BuildId: 58219892f2590f2e29f34622141ee178)
03-20 09:10:57.407 11674 11674 F DEBUG   :       #02 pc 0000000000003874  /system/lib64/libaudioeffect_jni.so (android_media_AudioEffect_native_setup(_JNIEnv*, _jobject*, _jobject*, _jstring*, _jstring*, int, int, _jintArray*, _jobjectArray*, _jstring*)+1376) (BuildId: 58219892f2590f2e29f34622141ee178)
03-20 09:10:57.407 11674 11674 F DEBUG   :       #03 pc 000000000029f188  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+312) (BuildId: 600a26b6da00607997f3350c09c9e3dec3da8b47)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #04 pc 0000000000136334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #05 pc 0000000000145064  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #06 pc 00000000002e343c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #07 pc 00000000002df45c  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+712) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #08 pc 00000000005a6bf8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirectRange+256) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #09 pc 0000000000130c14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct_range+20) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #10 pc 00000000001edf8a  /system/framework/framework.jar (android.media.audiofx.AudioEffect.<init>+122)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #11 pc 00000000005a3e60  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1192) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #12 pc 0000000000130914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #13 pc 00000000001f38f0  /system/framework/framework.jar (android.media.audiofx.Equalizer.<init>+8)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #14 pc 00000000005a3e60  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1192) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.408 11674 11674 F DEBUG   :       #15 pc 0000000000130914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #16 pc 00000000001be152  /data/app/org.moire.ultrasonic-A7-TC3OwU7IqdQ_LHWIdWQ==/oat/arm64/base.vdex (org.moire.ultrasonic.audiofx.EqualizerController.create+56)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #17 pc 00000000002b4380  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.10283172362094725612+240) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #18 pc 0000000000592cb8  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+944) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #19 pc 000000000013f468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #20 pc 00000000001365b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #21 pc 0000000000145084  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #22 pc 00000000002e343c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #23 pc 00000000002de334  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+928) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #24 pc 00000000005a4368  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+368) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #25 pc 0000000000130994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #26 pc 00000000001c4aac  /data/app/org.moire.ultrasonic-A7-TC3OwU7IqdQ_LHWIdWQ==/oat/arm64/base.vdex (org.moire.ultrasonic.service.LocalMediaPlayer$2.run+24)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #27 pc 00000000002b4380  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.10283172362094725612+240) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #28 pc 0000000000592cb8  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+944) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #29 pc 000000000013f468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #30 pc 00000000001a3078  /system/framework/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: 782358b17ee421ced8d8b61cf5a46e5b93036b03)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #31 pc 0000000000136334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #32 pc 0000000000145064  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #33 pc 00000000004b114c  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #34 pc 00000000004b221c  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.409 11674 11674 F DEBUG   :       #35 pc 00000000004f2784  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1172) (BuildId: a0de32d5cd8b6ef7386adb27fa34113b)
03-20 09:10:57.410 11674 11674 F DEBUG   :       #36 pc 00000000000e49b0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: e197188b8993d24c80d269ede338a1d0)
03-20 09:10:57.410 11674 11674 F DEBUG   :       #37 pc 0000000000083f88  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: e197188b8993d24c80d269ede338a1d0)
```

Debug log until the crash:

```
09:10:55.807: I TimberKoinLogger [init] declare Android Context 
09:10:55.810: I TimberKoinLogger loaded 38 definitions - 0.242917 ms 
09:10:55.872: D NavigationActivity$onCreate Navigated to org.moire.ultrasonic:id/mainFragment 
09:10:55.873: I MediaPlayerControllerImpl MediaPlayerControllerImpl constructed 
09:10:55.925: I MediaPlayerControllerImpl MediaPlayerControllerImpl constructed 
09:10:55.926: I MediaPlayerLifecycleSupport LifecycleSupport constructed 
09:10:55.931: D JukeboxMediaPlayer Jukebox Service setting enabled to false 
09:10:56.933: D JukeboxMediaPlayer Stopped Jukebox Service 
09:10:56.934: I MediaPlayerControllerImpl MediaPlayerControllerImpl created 
09:10:56.935: I MediaPlayerLifecycleSupport LifecycleSupport created 
09:10:56.960: I FileUtil Deserialized object from /data/user/0/org.moire.ultrasonic/cache/downloadstate.ser 
09:10:56.961: I DownloadQueueSerializer Deserialized currentPlayingIndex: 3, currentPlayingPosition: 224696 
09:10:56.964: I MediaPlayerLifecycleSupport Headset event for: null 
09:10:57.068: I Downloader Downloader created 
09:10:57.070: I ShufflePlayBuffer ShufflePlayBuffer created 
09:10:57.089: I LocalMediaPlayer LocalMediaPlayer created 
09:10:57.138: I CacheCleaner File system       : 6,05 GB of 52,54 GB available 
09:10:57.139: I CacheCleaner Cache limit       : 4,88 GB 
09:10:57.139: W MediaPlayerService --- Created Foreground notification 
09:10:57.140: I CacheCleaner Cache size before : 1,50 GB 
09:10:57.140: I CacheCleaner Minimum to delete : 0 B 
09:10:57.140: I MediaPlayerService MediaPlayerService created 
09:10:57.141: I CacheCleaner Deleted           : 0 B 
09:10:57.175: V MediaPlayerService play requested for 3 
09:10:57.189: V LocalMediaPlayer setCurrentPlaying DownloadFile (Entry(id=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, parent=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0], isDirectory=false, title=Karnage, album=Labotomie, albumId=null, artist=Tetra Hydro K, artistId=null, track=4, year=0, genre=Dub, contentType=null, suffix=mp3, transcodedContentType=null, transcodedSuffix=null, coverArt=null, size=8171285, songCount=null, duration=238, bitRate=null, path=Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, isVideo=false, starred=false, discNumber=1, type=null, created=null, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null)) 
09:10:57.196: I LocalMediaPlayer In updateRemoteControl, playerState: IDLE [0] 
09:10:57.207: I LegacyImageLoader createLargeUnknownImage 
09:10:57.221: I LocalMediaPlayer Next: IDLE -> IDLE (DownloadFile (Entry(id=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0]/05-Exode.mp3, parent=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0], isDirectory=false, title=Exode, album=Labotomie, albumId=null, artist=Tetra Hydro K feat. Panda Dub, artistId=null, track=5, year=0, genre=Dub, contentType=null, suffix=mp3, transcodedContentType=null, transcodedSuffix=null, coverArt=null, size=11434176, songCount=null, duration=331, bitRate=null, path=Tetra Hydro K - Labotomie (2016) [MP3 v0]/05-Exode.mp3, isVideo=false, starred=false, discNumber=1, type=null, created=null, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null))) 
09:10:57.222: I CancellableTask Starting thread for CheckCompletionTask (DownloadFile (Entry(id=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0]/05-Exode.mp3, parent=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0], isDirectory=false, title=Exode, album=Labotomie, albumId=null, artist=Tetra Hydro K feat. Panda Dub, artistId=null, track=5, year=0, genre=Dub, contentType=null, suffix=mp3, transcodedContentType=null, transcodedSuffix=null, coverArt=null, size=11434176, songCount=null, duration=331, bitRate=null, path=Tetra Hydro K - Labotomie (2016) [MP3 v0]/05-Exode.mp3, isVideo=false, starred=false, discNumber=1, type=null, created=null, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null))) 
09:10:57.222: I LocalMediaPlayer IDLE -> IDLE (DownloadFile (Entry(id=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, parent=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0], isDirectory=false, title=Karnage, album=Labotomie, albumId=null, artist=Tetra Hydro K, artistId=null, track=4, year=0, genre=Dub, contentType=null, suffix=mp3, transcodedContentType=null, transcodedSuffix=null, coverArt=null, size=8171285, songCount=null, duration=238, bitRate=null, path=Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, isVideo=false, starred=false, discNumber=1, type=null, created=null, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null))) 
09:10:57.229: I LocalMediaPlayer Preparing media player 
09:10:57.240: I LocalMediaPlayer IDLE -> PREPARING (DownloadFile (Entry(id=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, parent=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0], isDirectory=false, title=Karnage, album=Labotomie, albumId=null, artist=Tetra Hydro K, artistId=null, track=4, year=0, genre=Dub, contentType=null, suffix=mp3, transcodedContentType=null, transcodedSuffix=null, coverArt=null, size=8171285, songCount=null, duration=238, bitRate=null, path=Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, isVideo=false, starred=false, discNumber=1, type=null, created=null, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null))) 
09:10:57.255: W MediaPlayerService --- Updated notification 
09:10:57.274: I LocalMediaPlayer Media player prepared 
09:10:57.274: I LocalMediaPlayer PREPARING -> PREPARED (DownloadFile (Entry(id=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, parent=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0], isDirectory=false, title=Karnage, album=Labotomie, albumId=null, artist=Tetra Hydro K, artistId=null, track=4, year=0, genre=Dub, contentType=null, suffix=mp3, transcodedContentType=null, transcodedSuffix=null, coverArt=null, size=8171285, songCount=null, duration=238, bitRate=null, path=Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, isVideo=false, starred=false, discNumber=1, type=null, created=null, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null))) 
09:10:57.275: I LocalMediaPlayer Restarting player from position 224696 
09:10:57.279: I LocalMediaPlayer In updateRemoteControl, playerState: PREPARED [224696] 
09:10:57.289: I LocalMediaPlayer PREPARED -> PAUSED (DownloadFile (Entry(id=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, parent=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0], isDirectory=false, title=Karnage, album=Labotomie, albumId=null, artist=Tetra Hydro K, artistId=null, track=4, year=0, genre=Dub, contentType=null, suffix=mp3, transcodedContentType=null, transcodedSuffix=null, coverArt=null, size=8171285, songCount=null, duration=238, bitRate=null, path=Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, isVideo=false, starred=false, discNumber=1, type=null, created=null, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null))) 
09:10:57.293: I LocalMediaPlayer In updateRemoteControl, playerState: PAUSED [224696] 
09:10:57.301: I DownloadQueueSerializer Serialized currentPlayingIndex: 3, currentPlayingPosition: 224696 
09:10:57.311: I FileUtil Serialized object to /data/user/0/org.moire.ultrasonic/cache/downloadstate.ser 
09:10:57.320: W MediaPlayerService --- Updated notification 
09:10:57.322: I DownloadQueueSerializer Serialized currentPlayingIndex: 3, currentPlayingPosition: 224696 
09:10:57.325: I FileUtil Serialized object to /data/user/0/org.moire.ultrasonic/cache/downloadstate.ser 
09:11:10.226: I TimberKoinLogger [init] declare Android Context 
09:11:10.229: I TimberKoinLogger loaded 38 definitions - 0.269792 ms 
09:11:10.283: D NavigationActivity$onCreate Navigated to org.moire.ultrasonic:id/mainFragment 
09:11:10.284: I MediaPlayerControllerImpl MediaPlayerControllerImpl constructed 
09:11:10.337: I MediaPlayerControllerImpl MediaPlayerControllerImpl constructed 
09:11:10.338: I MediaPlayerLifecycleSupport LifecycleSupport constructed 
09:11:10.343: D JukeboxMediaPlayer Jukebox Service setting enabled to false 
09:11:11.345: D JukeboxMediaPlayer Stopped Jukebox Service 
09:11:11.346: I MediaPlayerControllerImpl MediaPlayerControllerImpl created 
09:11:11.347: I MediaPlayerLifecycleSupport LifecycleSupport created 
09:11:11.376: I FileUtil Deserialized object from /data/user/0/org.moire.ultrasonic/cache/downloadstate.ser 
09:11:11.377: I MediaPlayerLifecycleSupport Headset event for: null 
09:11:11.377: I DownloadQueueSerializer Deserialized currentPlayingIndex: 3, currentPlayingPosition: 224696 
09:11:11.474: I CacheCleaner File system       : 6,05 GB of 52,54 GB available 
09:11:11.475: I CacheCleaner Cache limit       : 4,88 GB 
09:11:11.475: I CacheCleaner Cache size before : 1,50 GB 
09:11:11.475: I CacheCleaner Minimum to delete : 0 B 
09:11:11.476: I CacheCleaner Deleted           : 0 B 
09:11:11.487: I Downloader Downloader created 
09:11:11.488: I ShufflePlayBuffer ShufflePlayBuffer created 
09:11:11.506: I LocalMediaPlayer LocalMediaPlayer created 
09:11:11.525: W MediaPlayerService --- Created Foreground notification 
09:11:11.525: I MediaPlayerService MediaPlayerService created 
09:11:11.533: V MediaPlayerService play requested for 3 
09:11:11.534: V LocalMediaPlayer setCurrentPlaying DownloadFile (Entry(id=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, parent=/storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/Tetra Hydro K - Labotomie (2016) [MP3 v0], isDirectory=false, title=Karnage, album=Labotomie, albumId=null, artist=Tetra Hydro K, artistId=null, track=4, year=0, genre=Dub, contentType=null, suffix=mp3, transcodedContentType=null, transcodedSuffix=null, coverArt=null, size=8171285, songCount=null, duration=238, bitRate=null, path=Tetra Hydro K - Labotomie (2016) [MP3 v0]/04-Karnage.mp3, isVideo=false, starred=false, discNumber=1, type=null, created=null, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null)) 
09:11:11.536: I LocalMediaPlayer In updateRemoteControl, playerState: IDLE [0] 
09:11:11.545: I LegacyImageLoader createLargeUnknownImage 
09:11:11.554: I FileUtil Deserialized object from /data/user/0/org.moire.ultrasonic/cache/equalizer.dat 
09:11:11.563: W EqualizerController Failed to load equalizer settings.
java.lang.UnsupportedOperationException: AudioEffect: invalid parameter operation
	at android.media.audiofx.AudioEffect.checkStatus(AudioEffect.java:1349)
	at android.media.audiofx.Equalizer.setBandLevel(Equalizer.java:223)
	at org.moire.ultrasonic.audiofx.EqualizerController$EqualizerSettings.apply(SourceFile:175)
	at org.moire.ultrasonic.audiofx.EqualizerController.loadSettings(SourceFile:135)
	at org.moire.ultrasonic.audiofx.EqualizerController.create(SourceFile:72)
	at org.moire.ultrasonic.service.LocalMediaPlayer$2.run(SourceFile:140)
	at java.lang.Thread.run(Thread.java:919)
 java.lang.UnsupportedOperationException: AudioEffect: invalid parameter operation
09:11:11.568: W VisualizerController Failed to create visualizer.
java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
	at android.media.audiofx.Visualizer.<init>(Visualizer.java:229)
	at org.moire.ultrasonic.audiofx.VisualizerController.create(SourceFile:65)
	at org.moire.ultrasonic.service.LocalMediaPlayer$2.run(SourceFile:141)
	at java.lang.Thread.run(Thread.java:919)
 java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
```

**Comment by nitehu** [comment]
I think the stacktrace wasn't saved because the crash was in the OS and not in Ultrasonic. Ultrasonic logs its own crashes into both the stacktrace file (even when there is already one present) and to the debug log file.
It is normal for the Equalizer and Visualizer to fail to initialize, that's why the log lines are only Warning. Ultrasonic usually survives that.

I'm not sure if there are more appropriate ways to detect the equalizer and/or the visualizer than trying to create them and catch  the exception when that fails, this may be investigated further.
