### ISSUE TITLE
getContext() can return null in Fragments

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#411]
In many fragments getContext() is used as if it always returned a value.
For example,
ArrayAdapter accepts only non--null context, but EntryAdapter hides this.

```
2021-04-02 08:57:15.031 2224-2224/org.moire.ultrasonic.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.moire.ultrasonic.debug, PID: 2224
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.view.LayoutInflater.from(LayoutInflater.java:284)
        at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:213)
        at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:207)
        at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:193)
        at org.moire.ultrasonic.view.EntryAdapter.<init>(EntryAdapter.java:46)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment$LoadTask.done(SelectAlbumFragment.kt:1047)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment$getAlbumList$1.done(SelectAlbumFragment.kt:800)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment$getAlbumList$1.done(SelectAlbumFragment.kt:742)
        at org.moire.ultrasonic.util.FragmentBackgroundTask$1$1.run(FragmentBackgroundTask.java:57)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
2021-04-02 08:57:15.057 2224-2224/org.moire.ultrasonic.debug E/SubsonicUncaughtExceptionHandler: Uncaught Exception! Android API level: 29
    Ultrasonic version name: 2.19.2
    Ultrasonic version code: 91
    
    
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.view.LayoutInflater.from(LayoutInflater.java:284)
        at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:213)
        at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:207)
        at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:193)
        at org.moire.ultrasonic.view.EntryAdapter.<init>(EntryAdapter.java:46)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment$LoadTask.done(SelectAlbumFragment.kt:1047)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment$getAlbumList$1.done(SelectAlbumFragment.kt:800)
        at org.moire.ultrasonic.fragment.SelectAlbumFragment$getAlbumList$1.done(SelectAlbumFragment.kt:742)
        at org.moire.ultrasonic.util.FragmentBackgroundTask$1$1.run(FragmentBackgroundTask.java:57)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by tzugen** [comment]
The best way to fix it cleanly, is to move more fragments to a MVVM pattern...
