### ISSUE TITLE
App crashes when pressing the album cover in player

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#415]
## System information
```

Android API level: 29
Ultrasonic version name: 2.19.2-DEVELOP
Ultrasonic version code: 91


java.lang.IllegalStateException: View android.widget.LinearLayout{f3e81d0 VFE...C.. ........ 0,0-1080,179 #7f0901a0 app:id/now_playing} does not have a NavController set
	at androidx.navigation.Navigation.findNavController(Navigation.java:84)
	at org.moire.ultrasonic.fragment.NowPlayingFragment$2.onClick(NowPlayingFragment.java:129)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
	
	
	
```

## Additional notes

Include any extra notes here. Otherwise you may remove this section.

**Comment by tzugen** [comment]
How to reproduce:
* Play a song
* Kill the app
* Reopen app
* On the bottom you should see the song you played
* Tap the cover
* Crash
