### ISSUE TITLE
Add error handling to SelectAlbumModel functions

### ISSUE THREAD

**Issue by nitehu** [ultrasonic/ultrasonic#484]
## Problem description

The functions in SelectAlbumModel were refactored to use coroutines instead of BackgroundTask. 
BackgroundTask was able to handle the occurred exceptions using CommunicationErrorHandler. Unfortunately this is now missing, so every communication error kills Ultrasonic here.

We should add back an error handler which catches and handles these exceptions in SelectAlbumModel.

Sample exception:

```
E/SubsonicUncaughtExceptionHandler: Uncaught Exception! Android API level: 30
    Ultrasonic version name: 2.20.0
    Ultrasonic version code: 92
    
    
    java.io.IOException: Server error, code: 400
        at org.moire.ultrasonic.service.ApiCallResponseChecker$Companion.checkResponseSuccessful(ApiCallResponseChecker.kt:55)
        at org.moire.ultrasonic.service.ApiCallResponseChecker.callWithResponseCheck(ApiCallResponseChecker.kt:41)
        at org.moire.ultrasonic.service.RESTMusicService.getMusicDirectory(RESTMusicService.kt:183)
        at org.moire.ultrasonic.service.CachedMusicService.getMusicDirectory(CachedMusicService.java:173)
        at org.moire.ultrasonic.fragment.SelectAlbumModel$getMusicDirectory$2.invokeSuspend(SelectAlbumModel.kt:76)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by tzugen** [comment]
I am working on a further refactor & will do it there
